-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 13:09:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sudokuDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sudokuDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sudokuDB` DEFAULT CHARACTER SET utf8 ;
USE `sudokuDB` ;

-- -----------------------------------------------------
-- Table `sudokuDB`.`JOUEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudokuDB`.`JOUEUR` (
  `id_joueur` INT NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `date_creation` DATE NOT NULL,
  `nationalite` VARCHAR(45) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `score` INT NOT NULL DEFAULT 0,
  `mot_de_passe` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_joueur`),
  UNIQUE INDEX `id_joueur_UNIQUE` (`id_joueur` ASC) VISIBLE,
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sudokuDB`.`JOUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudokuDB`.`JOUR` (
  `id_jour` INT NOT NULL,
  `date` DATE NOT NULL,
  `id_joueur` INT NOT NULL,
  PRIMARY KEY (`id_jour`),
  UNIQUE INDEX `id_jour_UNIQUE` (`id_jour` ASC) VISIBLE,
  INDEX `id_joueur_idx` (`id_joueur` ASC) VISIBLE,
  CONSTRAINT `id_joueur`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `sudokuDB`.`JOUEUR` (`id_joueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sudokuDB`.`SUDOKU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudokuDB`.`SUDOKU` (
  `id_sudoku` INT NOT NULL,
  `difficulte` INT NOT NULL,
  `case_init` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_sudoku`),
  UNIQUE INDEX `id_sudoku_UNIQUE` (`id_sudoku` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sudokuDB`.`SESSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudokuDB`.`SESSION` (
  `id_session` INT NOT NULL,
  `nbr_erreur` INT NULL,
  `temps` DATETIME NOT NULL,
  `id_jour` INT NOT NULL,
  `id_sudoku` INT NOT NULL,
  PRIMARY KEY (`id_session`),
  INDEX `id_jour_idx` (`id_jour` ASC) VISIBLE,
  INDEX `id_sudoku_idx` (`id_sudoku` ASC) VISIBLE,
  CONSTRAINT `id_jour`
    FOREIGN KEY (`id_jour`)
    REFERENCES `sudokuDB`.`JOUR` (`id_jour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_sudoku`
    FOREIGN KEY (`id_sudoku`)
    REFERENCES `sudokuDB`.`SUDOKU` (`id_sudoku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- INSERT INTO SUDOKU (id_sudoku, difficulte, case_init) VALUES (0,6,"A3:5,A4:3,A6:9,A7:4,A9:7,B9:5,C3:4,C6:8,C9:6,D1:8,D3:2,D4:9,D5:3,D6:6,E2:3,E6:4,E8:5,F1:7,F3:1,F6:5,G4:5,G5:8,G6:2,G8:3,G9:9,H3:8,H6:3,H8:4,I2:9,I3:6,I4:4,I7:5,I9:8");


-- INSERT INTO JOUEUR (id_joueur, pseudo, nom, prenom, date_creation, nationalite, date_naissance, score, mot_de_passe) VALUES (0, "Lililica", "TERRASSON", "Lucas", '2024-06-26', "France", '2003-07-05', 500, "root");
-- INSERT INTO JOUEUR (id_joueur, pseudo, nom, prenom, date_creation, nationalite, date_naissance, score, mot_de_passe) VALUES (1, "Nyny", "RUIZ", "Fanny", '2024-06-26', "France", '2003-09-24', 1560, "root2");
-- INSERT INTO JOUEUR (id_joueur, pseudo, nom, prenom, date_creation, nationalite, date_naissance, score, mot_de_passe) VALUES (2, "Xx_Gamer_xX", "RONALD", "McDonald", '2022-01-07', "Spain", '1989-12-15', 10196, "McDO965*B9");


-- INSERT INTO JOUR (id_jour, date, id_joueur) VALUES (0, '2024-06-24', 0);
-- INSERT INTO JOUR (id_jour, date, id_joueur) VALUES (1, '2024-07-24', 1);

-- INSERT INTO SESSION (id_session, nbr_erreur, temps, id_jour, id_sudoku) VALUES (0, 4, '00:30:12', 0, 0);
-- INSERT INTO SESSION (id_session, nbr_erreur, temps, id_jour, id_sudoku) VALUES (1, 2, '00:27:32', 1, 1);